language: go
go:
    - 1.8.x
    - 1.9.x
    - 1.10.x

install:
    - go get -u golang.org/x/tools/cmd/goimports
    - go get -u github.com/axw/gocov/gocov
    - go get -u github.com/t-yuki/gocov-xml
    - go get -u github.com/tebeka/go2xunit
    - go get -u github.com/alecthomas/gometalinter
    - gometalinter --install --vendor
    - curl https://glide.sh/get | sh

script:
  - make local test
