language: go
go:
    - 1.10.x
    - 1.11.x
    - 1.12.x

install:
    - go get -u golang.org/x/tools/cmd/goimports
    - go get -u github.com/axw/gocov/gocov
    - go get -u github.com/t-yuki/gocov-xml
    - go get -u github.com/tebeka/go2xunit
    - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
    - curl https://glide.sh/get | sh

script:
  - make local test
